Repository kwickbit/kwickbit_frontend_v0, pull requests merged in 2024-02, with the labels that each got.

#40 Bohdan issue 14
  .env.development
  src/components/CenterModal.tsx
  src/components/common/AppIcon.tsx
  src/components/integrations/IntegrationsView.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationCard.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/CurrencyLine.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/CurrencySelect.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/index.tsx
  src/hooks/integrations/quickbooks/index.ts
  src/hooks/integrations/quickbooks/useConnectToQuickbook.ts
  src/hooks/integrations/useQuickbookIntegrationModal.ts
  src/hooks/oauth2-providers/intuit.ts
  src/hooks/useWebSocket.tsx
  src/pages/integrations.tsx
  src/services/integrations.ts
  src/services/integrations/quickbooks.ts
  tailwind.config.ts
Labels: enhancement, ui, logic

#44 map to alternative currency or convert radio button
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/CurrencyLine.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/CurrencySelect.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/index.tsx
  src/services/integrations/quickbooks.ts
Labels: enhancement, ui, logic

#50 refacto transaction components for integration with QuickBooks
  src/components/common/AppIcon.tsx
  src/components/common/Select.tsx
  src/components/common/WarningAlert.tsx
  src/components/integrations/index.ts
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/CurrencyLine.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/CurrencySelect.tsx
  src/components/integrations/quickbooks/QuickBooksIntegrationModal/index.tsx
  src/components/transactions/EditTransactionModal/AccountingLines.tsx
  src/components/transactions/EditTransactionModal/BlockchainFee.tsx
  src/components/transactions/EditTransactionModal/CollectionLine.tsx
  src/components/transactions/EditTransactionModal/TransactionLines.tsx
  src/components/transactions/EditTransactionModal/footer.tsx
  src/components/transactions/EditTransactionModal/header.tsx
  src/components/transactions/EditTransactionModal/index.tsx
  src/components/transactions/TransactionListSection.tsx
  src/components/transactions/TransactionsView.tsx
  src/components/transactions/WarningAlert.tsx
  src/components/transactions/WarningLine.tsx
  src/hooks/transactions.ts
  src/hooks/transactions/EditTransactionModal/useCollectionLine.ts
  src/hooks/transactions/EditTransactionModal/useEditTransactionModal.ts
  src/hooks/transactions/EditTransactionModal/useTransactionLines.ts
  src/hooks/transactions/index.ts
  src/hooks/transactions/useTransactionsView.ts
  src/hooks/useQuickBooksDataProvider.tsx
  src/hooks/useWebSocket.tsx
  src/lib/helpers.ts
  src/lib/react-node-formatters.tsx
  src/services/integrations/quickbooks.ts
  src/services/token_currencies_conversions.ts
  src/services/transactions.ts
Labels: enhancement, ui, logic, coherence

#52 add small bug fixes
  README.md
  src/components/transactions/EditTransactionModal/index.tsx
Labels: bug
